apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: org-admins-iam
  namespace: yakima-system # kpt-set: ${management-namespace}
spec:
  member: group:yakima@google.com # kpt-set: group:${group-org-admins}
  role: roles/resourcemanager.organizationAdmin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Organization
    external: "123456789012" # kpt-set: ${org-id}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: billing-admins-iam
  namespace: yakima-system # kpt-set: ${management-namespace}
spec:
  member: group:yakima@google.com # kpt-set: group:${group-billing-admins}
  role: roles/billing.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Organization
    external: "123456789012" # kpt-set: ${org-id}
